CREATE TABLE [dbo].[Audit]
(
	[AuditId] UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL PRIMARY KEY,
	[UserId] UNIQUEIDENTIFIER NULL,
	[Username] NVARCHAR(250) NULL,
	[Class]  NVARCHAR(150) NULL,
	[Method]  NVARCHAR(250) NULL,
	[Entity] NVARCHAR(150) NULL,
	[EntityId] UNIQUEIDENTIFIER NULL,
	[RecordData] NVARCHAR(MAX) NULL,
	[CreatedOn] DATETIME2(7) NOT NULL DEFAULT GETDATE()
)

