CREATE TABLE Campaign(
	CampaignId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Name] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(2500) NOT NULL,
	[Strategy] NVARCHAR(2500) NOT NULL,
	StartDate DATE,
	EndDate DATE, 
    [State] BIT NOT NULL DEFAULT 1
	)