CREATE TABLE Client (
  ClientId  UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
  [Name] NVARCHAR(200) NOT NULL,
  [PhoneNumber] NVARCHAR(25) NOT NULL,
  [Contact] NVARCHAR(250) NOT NULL,
  Logo NVARCHAR(500) NOT NULL,
  [Prospect] BIT DEFAULT 0,
  Facebook NVARCHAR(1500)  NULL,
  Instagram NVARCHAR(1500)  NULL,
  LinkedIn NVARCHAR(1500)  NULL,
  [Description] NVARCHAR(MAX) NOT NULL,
  IndustryId UNIQUEIDENTIFIER NULL,
  Email NVARCHAR(250) NOT NULL,
  [State] BIT NOT NULL DEFAULT 1
);
GO
ALTER TABLE [dbo].[Client]
ADD FOREIGN KEY (IndustryId) REFERENCES Industry(IndustryId);
GO