CREATE TABLE [dbo].[LogBook]
(
	[LogBookId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID()  PRIMARY KEY,
	[UserId] UNIQUEIDENTIFIER NULL,
	[Username] NVARCHAR(350) NULL,
	[Class]  NVARCHAR(100) NULL,
	[Method]  NVARCHAR(100) NULL,
	[ExceptionMessage] NVARCHAR(MAX) NULL,
	[CreatedOn] DATETIME2(7) NULL DEFAULT GETDATE()
)
