CREATE TABLE Product(
	ProductId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
	[Name] NVARCHAR(50) NOT NULL, 
    [Description] NVARCHAR(1000) NULL, 
    [ImagePath] NVARCHAR(500) NULL, 
    [State] BIT NOT NULL DEFAULT 1
	)